### PR TITLE
Redesign the board

### PR DESCRIPTION
**Pull request by felixmosh**
This PR contains:

1. UI build improvement - enable css modules
2. Redesign the entire board.
3. Custom error stack highlighting

image
image

### CODE REVIEW

**Comment by vcapretz** [comment]
Hey @felixmosh, awesome work, I'll try taking some time to review this PR soon 😄 

Btw, I've been looking for some more maintainers in this project, is that something you would be interested? If so, maybe shoot me a DM on twitter [@vcapretz]( https://twitter.com/vcapretz) so we can talk about it!

**Comment by felixmosh** [comment]
@vcapretz did you had a chance to review this PR?

**Comment by eialanjones** [comment]
impressive work @felixmosh! Do u have a npm version of your branch?

**Comment by felixmosh** [comment]
@eialanjones No, I want it to be merged to the official repo.

**Review by eialanjones — APPROVED** [review]
An masterpiece of work.

**Review by vcapretz — APPROVED** [review]

**Pull request merged**
